-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:20194231fac19d735497ce2a76736383$
-- 

return {
	texture = 'sprites2.png',
	frames = {
			{
				name = "100x100__0000_background-box2.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.421053, v0 = 0, u1 = 0.526316, v1 = 1 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0000_background-boxe.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.315789, v0 = 0, u1 = 0.421053, v1 = 1 },
				spriteSourceSize = { width = 99, height = 98 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "100x100__0001_metal-covered-b.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.210526, v0 = 0, u1 = 0.315789, v1 = 1 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0003_large-covered.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.105263, v0 = 0, u1 = 0.210526, v1 = 1 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0005_steel-girder.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.105263, v1 = 1 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x50__0002_2x1-box.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 50 },
				uvRect = { u0 = 0.631579, v0 = 0, u1 = 0.736842, v1 = 0.5 },
				spriteSourceSize = { width = 100, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x50__0002_tall-box-goat.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 100 },
				uvRect = { u0 = 0.578947, v0 = 0, u1 = 0.631579, v1 = 1 },
				spriteSourceSize = { width = 50, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x100__0001_tall-box-TOP.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 100 },
				uvRect = { u0 = 0.526316, v0 = 0, u1 = 0.578947, v1 = 1 },
				spriteSourceSize = { width = 50, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0000_marker.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.947368, v0 = 0.5, u1 = 1, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0001_darkened-tile.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.947368, v0 = 0, u1 = 1, v1 = 0.5 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0002_Layer-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.894737, v0 = 0.5, u1 = 0.947368, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0003_concrete-square.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.894737, v0 = 0, u1 = 0.947368, v1 = 0.5 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0004_tilted-box-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.842105, v0 = 0.5, u1 = 0.894737, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0005_1x1-leaking-box.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.842105, v0 = 0, u1 = 0.894737, v1 = 0.5 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0000_cracks-5.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.789474, v0 = 0.5, u1 = 0.842105, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0001_cracks-4.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.789474, v0 = 0, u1 = 0.842105, v1 = 0.5 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0002_cracks-3.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.736842, v0 = 0.5, u1 = 0.789474, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0003_cracks-2.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.736842, v0 = 0, u1 = 0.789474, v1 = 0.5 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0004_cracks-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.684211, v0 = 0.5, u1 = 0.736842, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0005_tilted-box-2.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.631579, v0 = 0.5, u1 = 0.684211, v1 = 1 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

