-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:3e7b925ed105062f40a9ca5fdd4e15b7$
-- 

return {
	texture = 'sprites.png',
	frames = {
			{
				name = "100x100__0000_background-box2.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.195312, v1 = 0.390625 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0000_background-boxe.png",
				spriteColorRect = { x = 0, y = 0, width = 99, height = 98 },
				uvRect = { u0 = 0.195312, v0 = 0, u1 = 0.388672, v1 = 0.382812 },
				spriteSourceSize = { width = 99, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0001_metal-covered-b.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.388672, v0 = 0, u1 = 0.583984, v1 = 0.390625 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0003_large-covered.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.583984, v0 = 0, u1 = 0.779297, v1 = 0.390625 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0004_top-girder.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.779297, v0 = 0, u1 = 0.974609, v1 = 0.390625 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x100__0005_steel-girder.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0, v0 = 0.390625, u1 = 0.195312, v1 = 0.78125 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x50__0002_2x1-box.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 50 },
				uvRect = { u0 = 0.195312, v0 = 0.390625, u1 = 0.390625, v1 = 0.585938 },
				spriteSourceSize = { width = 100, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "100x50__0002_tall-box-goat.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 100 },
				uvRect = { u0 = 0.390625, v0 = 0.390625, u1 = 0.488281, v1 = 0.78125 },
				spriteSourceSize = { width = 50, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x100__0001_tall-box-TOP.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 100 },
				uvRect = { u0 = 0.488281, v0 = 0.390625, u1 = 0.585938, v1 = 0.78125 },
				spriteSourceSize = { width = 50, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0000_marker.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.585938, v0 = 0.390625, u1 = 0.683594, v1 = 0.585938 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0001_darkened-tile.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.683594, v0 = 0.390625, u1 = 0.78125, v1 = 0.585938 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0002_Layer-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.78125, v0 = 0.390625, u1 = 0.878906, v1 = 0.585938 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0003_concrete-square.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.878906, v0 = 0.390625, u1 = 0.976562, v1 = 0.585938 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0004_tilted-box-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0, v0 = 0.78125, u1 = 0.0976562, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0005_1x1-leaking-box.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.0976562, v0 = 0.78125, u1 = 0.195312, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50_0008_Background.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.195312, v0 = 0.78125, u1 = 0.292969, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0000_cracks-5.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.292969, v0 = 0.78125, u1 = 0.390625, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0001_cracks-4.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.390625, v0 = 0.78125, u1 = 0.488281, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0002_cracks-3.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.488281, v0 = 0.78125, u1 = 0.585938, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0003_cracks-2.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.585938, v0 = 0.78125, u1 = 0.683594, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0004_cracks-1.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.683594, v0 = 0.78125, u1 = 0.78125, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "50x50__0005_tilted-box-2.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0.78125, v0 = 0.78125, u1 = 0.878906, v1 = 0.976562 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

